// The 29 constituencies: [number, areas in English, areas in Marathi]. English goes in `wards.name`,
// Marathi in `wards.name_mr`. (The Marathi is a transliteration/translation by an AI assistant - please
// have a native speaker check the place names.) `areas` is stored in the `wards.name` column (the app calls wards
// "constituencies" everywhere users can see them; the database/API identifiers keep the original
// `ward` names). Used by scripts/seed.js and scripts/load-constituencies.js.
export const CONSTITUENCIES = [
  [1, 'Harsool, Fatema Nagar, Pisadevi Road, Morya Park, and northern peri-urban zones',
    'हर्सूल, फातिमा नगर, पिसादेवी रोड, मोरया पार्क आणि उत्तरेकडील उपनगरी भाग'],
  [2, 'Bharatnagar, Wankhedenagar, Yadavnagar, Honajinagar, and MSEB Power House areas',
    'भारतनगर, वानखेडेनगर, यादवनगर, होनाजीनगर आणि एमएसईबी पॉवर हाऊस परिसर'],
  [3, 'Mayur Park, Surewadi, and adjoining CIDCO N-11 fringes',
    'मयूर पार्क, सुरेवाडी आणि लगतचा सिडको एन-11 परिसर'],
  [4, 'Padegaon, Mitmita, Police Colony, Vikaspuri, and Kasliwal Tarangan',
    'पडेगाव, मिटमिटा, पोलीस कॉलनी, विकासपुरी आणि कासलीवाल तारांगण'],
  [5, 'Bhawsingpura, Sanchi Gate, Shantipura, and Nandanvan Colony',
    'भावसिंगपुरा, सांची गेट, शांतीपुरा आणि नंदनवन कॉलनी'],
  [6, 'Dr. Babasaheb Ambedkar Marathwada University campus, Pahadsingpura, and Begumpura',
    'डॉ. बाबासाहेब आंबेडकर मराठवाडा विद्यापीठ परिसर, पहाडसिंगपुरा आणि बेगमपुरा'],
  [7, 'Jaisingpura, Aref Colony, Pragati Nagar, and surrounding northern pockets',
    'जयसिंगपुरा, आरेफ कॉलनी, प्रगती नगर आणि आसपासचे उत्तरेकडील भाग'],
  [8, 'Jaibhimnagar, Asefia Colony, Buddhilane, and Kabadipura',
    'जयभीमनगर, आसेफिया कॉलनी, बुद्धिलेन आणि कबाडीपुरा'],
  [9, 'Lota Karanja, Chelipura, Kachiwada, and nearby old-city quarters',
    'लोटा कारंजा, चेलीपुरा, कचीवाडा आणि जवळचे जुन्या शहरातील भाग'],
  [10, 'Shahabazar, Ganesh Colony, and Nehru Nagar',
    'शहाबाजार, गणेश कॉलनी आणि नेहरू नगर'],
  [11, 'Shatabdi Nagar, Swami Vivekanand Nagar, and Shrikrishna Nagar',
    'शताब्दी नगर, स्वामी विवेकानंद नगर आणि श्रीकृष्ण नगर'],
  [12, 'Pawan Nagar, Misarwadi, and Aarti Nagar',
    'पवन नगर, मिसारवाडी आणि आरती नगर'],
  [13, 'Naregaon, Brijwadi, and the eastern suburban belt',
    'नारेगाव, ब्रिजवाडी आणि पूर्वेकडील उपनगरी पट्टा'],
  [14, 'Choudhari Colony and the Chikalthana MIDC industrial belt',
    'चौधरी कॉलनी आणि चिकलठाणा एमआयडीसी औद्योगिक पट्टा'],
  [15, 'Ayodhya Nagar, Ganesh Nagar, and surrounding transport corridor localities',
    'अयोध्या नगर, गणेश नगर आणि आसपासचे वाहतूक मार्गिकेवरील परिसर'],
  [16, 'Kiradpura, Sharif Colony, and Rehmaniya Colony',
    'किराडपुरा, शरीफ कॉलनी आणि रहमानिया कॉलनी'],
  [17, 'Roshan Gate, Kaisar Colony, and Nawabpura',
    'रोशन गेट, कैसर कॉलनी आणि नवाबपुरा'],
  [18, 'Raja Bazar, Gulmandi, and Khadkeshwar market hubs',
    'राजाबाजार, गुलमंडी आणि खडकेश्वर बाजारपेठ परिसर'],
  [19, 'Kranti Chowk, Ramanagar, Pannalal Nagar, Sant Eknath Rang Mandir area, and Shahanurwadi',
    'क्रांती चौक, रमानगर, पन्नालाल नगर, संत एकनाथ रंगमंदिर परिसर आणि शहानूरवाडी'],
  [20, 'Balaji Nagar, Tilak Nagar, Shivshankar Colony, Ravindra Nagar, and Dnyaneshwar Nagar',
    'बालाजी नगर, टिळक नगर, शिवशंकर कॉलनी, रवींद्र नगर आणि ज्ञानेश्वर नगर'],
  [21, 'Jawahar Colony, Vishnu Nagar, Sindhi Colony, Ulkanagari, and Kabra Nagar',
    'जवाहर कॉलनी, विष्णू नगर, सिंधी कॉलनी, उल्कानगरी आणि काबरा नगर'],
  [22, 'CIDCO N-6, Awishkar Colony, and surrounding planned commercial-residential sectors',
    'सिडको एन-6, आविष्कार कॉलनी आणि आसपासचे नियोजित व्यापारी-निवासी सेक्टर'],
  [23, 'CIDCO N-3, N-4, Parijat Nagar, and Nyaya Nagar',
    'सिडको एन-3, एन-4, पारिजात नगर आणि न्याय नगर'],
  [24, 'Samarth Nagar, Sillekhana, and Samta Nagar',
    'समर्थ नगर, सिल्लेखाना आणि समता नगर'],
  [25, 'Usmanpura, Padampura, and Railway Station vicinity',
    'उस्मानपुरा, पदमपुरा आणि रेल्वे स्टेशन परिसर'],
  [26, 'Garkheda Parisar, Sutgirni Chowk, and Mayur Nagari',
    'गारखेडा परिसर, सूतगिरणी चौक आणि मयूर नगरी'],
  [27, 'Ulkanagari extension, Dashmesh Nagar, and Shahnoor Miya Dargah zone',
    'उल्कानगरी विस्तार, दशमेश नगर आणि शहानूर मिया दर्गा परिसर'],
  [28, 'Satara Parisar, Beed Bypass (West), and Kanchanwadi road corridors',
    'सातारा परिसर, बीड बायपास (पश्चिम) आणि कांचनवाडी रस्त्यालगतचे भाग'],
  [29, 'Deolai, Beed Bypass (East), and southern border development corridors',
    'देवळाई, बीड बायपास (पूर्व) आणि दक्षिण सीमेवरील विकास मार्गिका'],
];
