// The 29 constituencies. `areas` is stored in the `wards.name` column (the app calls wards
// "constituencies" everywhere users can see them; the database/API identifiers keep the original
// `ward` names). Used by scripts/seed.js and scripts/load-constituencies.js.
export const CONSTITUENCIES = [
  [1, 'Harsool, Fatema Nagar, Pisadevi Road, Morya Park, and northern peri-urban zones'],
  [2, 'Bharatnagar, Wankhedenagar, Yadavnagar, Honajinagar, and MSEB Power House areas'],
  [3, 'Mayur Park, Surewadi, and adjoining CIDCO N-11 fringes'],
  [4, 'Padegaon, Mitmita, Police Colony, Vikaspuri, and Kasliwal Tarangan'],
  [5, 'Bhawsingpura, Sanchi Gate, Shantipura, and Nandanvan Colony'],
  [6, 'Dr. Babasaheb Ambedkar Marathwada University campus, Pahadsingpura, and Begumpura'],
  [7, 'Jaisingpura, Aref Colony, Pragati Nagar, and surrounding northern pockets'],
  [8, 'Jaibhimnagar, Asefia Colony, Buddhilane, and Kabadipura'],
  [9, 'Lota Karanja, Chelipura, Kachiwada, and nearby old-city quarters'],
  [10, 'Shahabazar, Ganesh Colony, and Nehru Nagar'],
  [11, 'Shatabdi Nagar, Swami Vivekanand Nagar, and Shrikrishna Nagar'],
  [12, 'Pawan Nagar, Misarwadi, and Aarti Nagar'],
  [13, 'Naregaon, Brijwadi, and the eastern suburban belt'],
  [14, 'Choudhari Colony and the Chikalthana MIDC industrial belt'],
  [15, 'Ayodhya Nagar, Ganesh Nagar, and surrounding transport corridor localities'],
  [16, 'Kiradpura, Sharif Colony, and Rehmaniya Colony'],
  [17, 'Roshan Gate, Kaisar Colony, and Nawabpura'],
  [18, 'Raja Bazar, Gulmandi, and Khadkeshwar market hubs'],
  [19, 'Kranti Chowk, Ramanagar, Pannalal Nagar, Sant Eknath Rang Mandir area, and Shahanurwadi'],
  [20, 'Balaji Nagar, Tilak Nagar, Shivshankar Colony, Ravindra Nagar, and Dnyaneshwar Nagar'],
  [21, 'Jawahar Colony, Vishnu Nagar, Sindhi Colony, Ulkanagari, and Kabra Nagar'],
  [22, 'CIDCO N-6, Awishkar Colony, and surrounding planned commercial-residential sectors'],
  [23, 'CIDCO N-3, N-4, Parijat Nagar, and Nyaya Nagar'],
  [24, 'Samarth Nagar, Sillekhana, and Samta Nagar'],
  [25, 'Usmanpura, Padampura, and Railway Station vicinity'],
  [26, 'Garkheda Parisar, Sutgirni Chowk, and Mayur Nagari'],
  [27, 'Ulkanagari extension, Dashmesh Nagar, and Shahnoor Miya Dargah zone'],
  [28, 'Satara Parisar, Beed Bypass (West), and Kanchanwadi road corridors'],
  [29, 'Deolai, Beed Bypass (East), and southern border development corridors'],
];
